#pragma once

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* One entry of the audio index. idx is the flat word index. */
typedef struct {
    uint16_t idx;
    uint32_t off; /* offset into audio_blob.bin */
    uint32_t len; /* mp3 byte length */
} gl_audio_entry_t;

/* Generated by firmware/tools/gen_audio.py (CI). */
extern const gl_audio_entry_t GL_AUDIO_INDEX[];
extern const uint32_t GL_AUDIO_COUNT;

/* Spawn the audio task (no-op on failure, device still works without audio). */
void gl_audio_init(void);

/* True when word_idx has a synthesized mp3 in the blob. */
bool gl_audio_available(uint16_t word_idx);

/* Asynchronously play (interrupts current playback). */
void gl_audio_play(uint16_t word_idx);

/* Stop current playback. */
void gl_audio_stop(void);

#ifdef __cplusplus
}
#endif
