#include "gl_data.h"

static const gl_word_t GL_A1[] = {
    {.german = "der Mann", .phonetic = "dɛr man",
    .chinese = "男人；丈夫",
    .example = "Der Mann liest eine Zeitung.", .example_cn = "这个男人在看报纸。",},
    {.german = "die Frau", .phonetic = "diː fʁaʊ",
    .chinese = "女人；妻子",
    .example = "Die Frau arbeitet im Büro.", .example_cn = "这位女士在办公室工作。",},
    {.german = "das Kind", .phonetic = "das kɪnt",
    .chinese = "孩子",
    .example = "Das Kind spielt im Garten.", .example_cn = "孩子在花园里玩。",},
    {.german = "das Haus", .phonetic = "das haʊs",
    .chinese = "房子；家",
    .example = "Mein Haus ist klein aber schön.", .example_cn = "我的房子小但漂亮。",},
    {.german = "die Familie", .phonetic = "diː famiːliə",
    .chinese = "家庭；家人",
    .example = "Meine Familie wohnt in Berlin.", .example_cn = "我的家人住在柏林。",},
    {.german = "die Schule", .phonetic = "diː ˈʃuːlə",
    .chinese = "学校",
    .example = "Die Schule beginnt um acht Uhr.", .example_cn = "学校八点开始上课。",},
    {.german = "das Wasser", .phonetic = "das ˈvasɐ",
    .chinese = "水",
    .example = "Ich trinke gern Wasser.", .example_cn = "我喜欢喝水。",},
    {.german = "der Tag", .phonetic = "deːɐ̯ taːk",
    .chinese = "白天；日子",
    .example = "Heute ist ein schöner Tag.", .example_cn = "今天是美好的一天。",},
    {.german = "die Nacht", .phonetic = "diː naxt",
    .chinese = "夜晚",
    .example = "In der Nacht schlafe ich gut.", .example_cn = "我夜里睡得很好。",},
    {.german = "der Morgen", .phonetic = "deːɐ̯ ˈmɔʁɡn̩",
    .chinese = "早晨",
    .example = "Am Morgen trinke ich Kaffee.", .example_cn = "早晨我喝咖啡。",},
    {.german = "der Abend", .phonetic = "deːɐ̯ ˈaːbənt",
    .chinese = "傍晚",
    .example = "Am Abend sehe ich fern.", .example_cn = "晚上我看电视。",},
    {.german = "das Jahr", .phonetic = "das jaːɐ̯",
    .chinese = "年",
    .example = "Das Jahr hat zwölf Monate.", .example_cn = "一年有十二个月。",},
    {.german = "die Zeit", .phonetic = "diː tsaɪt",
    .chinese = "时间",
    .example = "Ich habe keine Zeit.", .example_cn = "我没有时间。",},
    {.german = "der Freund", .phonetic = "deːɐ̯ fʁɔʏnt",
    .chinese = "朋友",
    .example = "Mein Freund heißt Max.", .example_cn = "我的朋友叫马克斯。",},
    {.german = "die Freundin", .phonetic = "diː ˈfʁɔʏndɪn",
    .chinese = "女朋友；女性朋友",
    .example = "Anna ist meine beste Freundin.", .example_cn = "安娜是我最好的朋友。",},
    {.german = "die Stadt", .phonetic = "diː ʃtat",
    .chinese = "城市",
    .example = "Hamburg ist eine große Stadt.", .example_cn = "汉堡是一座大城市。",},
    {.german = "das Land", .phonetic = "das lant",
    .chinese = "国家；乡村",
    .example = "Deutschland ist ein schönes Land.", .example_cn = "德国是一个美丽的国家。",},
    {.german = "die Straße", .phonetic = "diː ˈʃtʁaːsə",
    .chinese = "街道",
    .example = "Die Straße ist sehr lang.", .example_cn = "这条街很长。",},
    {.german = "das Essen", .phonetic = "das ˈɛsn̩",
    .chinese = "食物；吃饭",
    .example = "Das Essen schmeckt gut.", .example_cn = "饭菜很好吃。",},
    {.german = "das Brot", .phonetic = "das bʁoːt",
    .chinese = "面包",
    .example = "Zum Frühstück esse ich Brot.", .example_cn = "早餐我吃面包。",},
    {.german = "der Apfel", .phonetic = "deːɐ̯ ˈapfl̩",
    .chinese = "苹果",
    .example = "Der Apfel ist rot.", .example_cn = "这个苹果是红的。",},
    {.german = "die Milch", .phonetic = "diː mɪlç",
    .chinese = "牛奶",
    .example = "Ich trinke Milch zum Frühstück.", .example_cn = "我早餐喝牛奶。",},
    {.german = "der Kaffee", .phonetic = "deːɐ̯ kaˈfeː",
    .chinese = "咖啡",
    .example = "Möchtest du einen Kaffee?", .example_cn = "你想来杯咖啡吗？",},
    {.german = "das Geld", .phonetic = "das gɛlt",
    .chinese = "钱",
    .example = "Ich habe kein Geld dabei.", .example_cn = "我身上没带钱。",},
    {.german = "die Arbeit", .phonetic = "diː ˈaʁbaɪt",
    .chinese = "工作",
    .example = "Meine Arbeit macht mir Spaß.", .example_cn = "我的工作让我开心。",},
    {.german = "sein", .phonetic = "zaɪn",
    .chinese = "是；存在",
    .example = "Ich bin Student.", .example_cn = "我是学生。",},
    {.german = "haben", .phonetic = "ˈhaːbn̩",
    .chinese = "有；拥有",
    .example = "Ich habe einen Hund.", .example_cn = "我有一只狗。",},
    {.german = "gehen", .phonetic = "ˈgeːən",
    .chinese = "走；去",
    .example = "Wir gehen ins Kino.", .example_cn = "我们去看电影。",},
    {.german = "kommen", .phonetic = "ˈkɔmən",
    .chinese = "来",
    .example = "Woher kommst du?", .example_cn = "你从哪里来？",},
    {.german = "essen", .phonetic = "ˈɛsn̩",
    .chinese = "吃",
    .example = "Was isst du gern?", .example_cn = "你喜欢吃什么？",},
    {.german = "trinken", .phonetic = "ˈtʁɪŋkn̩",
    .chinese = "喝",
    .example = "Ich trinke jeden Tag Tee.", .example_cn = "我每天喝茶。",},
    {.german = "sprechen", .phonetic = "ˈʃpʁɛçn̩",
    .chinese = "说话",
    .example = "Sprechen Sie Deutsch?", .example_cn = "您会说德语吗？",},
    {.german = "lernen", .phonetic = "ˈlɛʁnən",
    .chinese = "学习",
    .example = "Ich lerne Deutsch seit einem Jahr.", .example_cn = "我学德语一年了。",},
    {.german = "wohnen", .phonetic = "ˈvoːnən",
    .chinese = "居住",
    .example = "Ich wohne in München.", .example_cn = "我住在慕尼黑。",},
    {.german = "arbeiten", .phonetic = "ˈaʁbaɪtn̩",
    .chinese = "工作",
    .example = "Sie arbeitet als Ärztin.", .example_cn = "她是医生。",},
    {.german = "fahren", .phonetic = "ˈfaːʁən",
    .chinese = "乘坐；驾驶",
    .example = "Ich fahre mit dem Bus.", .example_cn = "我坐公交车。",},
    {.german = "lesen", .phonetic = "ˈleːzn̩",
    .chinese = "阅读",
    .example = "Ich lese jeden Abend ein Buch.", .example_cn = "我每晚读书。",},
    {.german = "schreiben", .phonetic = "ˈʃʁaɪbn̩",
    .chinese = "写",
    .example = "Kannst du das bitte schreiben?", .example_cn = "你能写下这个吗？",},
    {.german = "kaufen", .phonetic = "ˈkaʊfn̩",
    .chinese = "购买",
    .example = "Ich kaufe ein neues Handy.", .example_cn = "我买一部新手机。",},
    {.german = "machen", .phonetic = "ˈmaxn̩",
    .chinese = "做；制作",
    .example = "Was machst du heute?", .example_cn = "你今天做什么？",},
    {.german = "gut", .phonetic = "guːt",
    .chinese = "好的",
    .example = "Das Essen ist sehr gut.", .example_cn = "饭菜非常好。",},
    {.german = "schlecht", .phonetic = "ʃlɛçt",
    .chinese = "坏的；差的",
    .example = "Das Wetter ist heute schlecht.", .example_cn = "今天天气不好。",},
    {.german = "groß", .phonetic = "ɡʁoːs",
    .chinese = "大的",
    .example = "Berlin ist eine große Stadt.", .example_cn = "柏林是一座大城市。",},
    {.german = "klein", .phonetic = "klaɪn",
    .chinese = "小的",
    .example = "Das Auto ist zu klein.", .example_cn = "这辆车太小了。",},
    {.german = "neu", .phonetic = "nɔʏ",
    .chinese = "新的",
    .example = "Mein Handy ist neu.", .example_cn = "我的手机是新的。",},
    {.german = "alt", .phonetic = "alt",
    .chinese = "老的；旧的",
    .example = "Das Haus ist sehr alt.", .example_cn = "这房子很老了。",},
    {.german = "schön", .phonetic = "ʃøːn",
    .chinese = "美丽的；好的",
    .example = "Der Garten ist schön.", .example_cn = "花园很美。",},
    {.german = "gern", .phonetic = "ɡɛʁn",
    .chinese = "喜欢地（做某事）",
    .example = "Ich schwimme gern.", .example_cn = "我喜欢游泳。",},
    {.german = "heute", .phonetic = "ˈhɔʏtə",
    .chinese = "今天",
    .example = "Heute habe ich frei.", .example_cn = "今天我休息。",},
    {.german = "morgen", .phonetic = "ˈmɔʁɡn̩",
    .chinese = "明天",
    .example = "Morgen fahre ich nach Köln.", .example_cn = "明天我去科隆。",},
};

static const gl_word_t GL_A2[] = {
    {.german = "die Reise", .phonetic = "diː ˈʁaɪzə",
    .chinese = "旅行",
    .example = "Die Reise nach Italien war toll.", .example_cn = "去意大利的旅行很棒。",},
    {.german = "der Bahnhof", .phonetic = "deːɐ̯ ˈbaːnhoːf",
    .chinese = "火车站",
    .example = "Der Zug kommt am Bahnhof an.", .example_cn = "火车到达火车站。",},
    {.german = "das Ticket", .phonetic = "das ˈtɪkɛt",
    .chinese = "车票；门票",
    .example = "Ich habe das Ticket online gekauft.", .example_cn = "我在网上买了票。",},
    {.german = "der Flug", .phonetic = "deːɐ̯ fluːk",
    .chinese = "航班",
    .example = "Der Flug hat zwei Stunden Verspätung.", .example_cn = "航班延误了两小时。",},
    {.german = "das Hotel", .phonetic = "das hoˈtɛl",
    .chinese = "酒店",
    .example = "Das Hotel liegt am Meer.", .example_cn = "酒店在海边。",},
    {.german = "die Umwelt", .phonetic = "diː ˈʊmvɛlt",
    .chinese = "环境",
    .example = "Wir müssen die Umwelt schützen.", .example_cn = "我们必须保护环境。",},
    {.german = "die Gesundheit", .phonetic = "diː gəˈzʊnthaɪt",
    .chinese = "健康",
    .example = "Sport ist gut für die Gesundheit.", .example_cn = "运动有益健康。",},
    {.german = "der Arzt", .phonetic = "deːɐ̯ aʁtst",
    .chinese = "医生",
    .example = "Ich gehe morgen zum Arzt.", .example_cn = "我明天去看医生。",},
    {.german = "das Krankenhaus", .phonetic = "das ˈkʁaŋkn̩haʊs",
    .chinese = "医院",
    .example = "Sie arbeitet im Krankenhaus.", .example_cn = "她在医院工作。",},
    {.german = "der Beruf", .phonetic = "deːɐ̯ bəˈʁuːf",
    .chinese = "职业",
    .example = "Was sind Sie von Beruf?", .example_cn = "您的职业是什么？",},
    {.german = "die Firma", .phonetic = "diː ˈfɪʁma",
    .chinese = "公司",
    .example = "Die Firma hat neue Mitarbeiter.", .example_cn = "公司有新员工了。",},
    {.german = "der Termin", .phonetic = "deːɐ̯ tɛɐ̯ˈmiːn",
    .chinese = "预约；约见",
    .example = "Ich habe morgen einen Termin.", .example_cn = "我明天有个预约。",},
    {.german = "das Gehalt", .phonetic = "das gəˈhalt",
    .chinese = "工资",
    .example = "Er ist mit seinem Gehalt zufrieden.", .example_cn = "他对工资满意。",},
    {.german = "die Wohnung", .phonetic = "diː ˈvɔːnʊŋ",
    .chinese = "住房；公寓",
    .example = "Meine Wohnung hat drei Zimmer.", .example_cn = "我的公寓有三个房间。",},
    {.german = "die Miete", .phonetic = "diː ˈmiːtə",
    .chinese = "租金",
    .example = "Die Miete ist jeden Monat zu zahlen.", .example_cn = "租金每月支付。",},
    {.german = "der Einkauf", .phonetic = "deːɐ̯ ˈaɪnkaʊf",
    .chinese = "购物",
    .example = "Der Einkauf hat zwanzig Euro gekostet.", .example_cn = "这次购物花了二十欧元。",},
    {.german = "die Kleidung", .phonetic = "diː ˈklaɪdʊŋ",
    .chinese = "衣服",
    .example = "Diese Kleidung ist zu teuer.", .example_cn = "这些衣服太贵了。",},
    {.german = "das Geschenk", .phonetic = "das gəˈʃɛŋk",
    .chinese = "礼物",
    .example = "Zum Geburtstag bekomme ich ein Geschenk.", .example_cn = "生日时我收到礼物。",},
    {.german = "die Einladung", .phonetic = "diː ˈaɪnladʊŋ",
    .chinese = "邀请",
    .example = "Danke für die Einladung zur Party.", .example_cn = "感谢邀请我参加聚会。",},
    {.german = "besuchen", .phonetic = "bəˈzuːxən",
    .chinese = "拜访；参观",
    .example = "Ich besuche meine Großeltern.", .example_cn = "我去看望祖父母。",},
    {.german = "brauchen", .phonetic = "ˈbʁaʊxən",
    .chinese = "需要",
    .example = "Ich brauche deine Hilfe.", .example_cn = "我需要你的帮助。",},
    {.german = "bezahlen", .phonetic = "bəˈtsaːlən",
    .chinese = "支付",
    .example = "Ich möchte mit Karte bezahlen.", .example_cn = "我想刷卡支付。",},
    {.german = "anbieten", .phonetic = "ˈanbiːtən",
    .chinese = "提供",
    .example = "Das Restaurant bietet vegetarisches Essen an.", .example_cn = "这家餐厅提供素食。",},
    {.german = "erzählen", .phonetic = "ɛɐ̯ˈtɛːlən",
    .chinese = "讲述",
    .example = "Er erzählt eine lustige Geschichte.", .example_cn = "他讲了一个有趣的故事。",},
    {.german = "verstehen", .phonetic = "fɛɐ̯ˈʃteːən",
    .chinese = "理解",
    .example = "Ich verstehe dich gut.", .example_cn = "我很理解你。",},
    {.german = "erklären", .phonetic = "ɛɐ̯ˈklɛːʁən",
    .chinese = "解释",
    .example = "Kannst du das noch mal erklären?", .example_cn = "你能再解释一遍吗？",},
    {.german = "versuchen", .phonetic = "fɛɐ̯ˈzuːxən",
    .chinese = "尝试",
    .example = "Ich versuche, pünktlich zu sein.", .example_cn = "我尽量准时。",},
    {.german = "vergessen", .phonetic = "fɛɐ̯ˈɡɛsn̩",
    .chinese = "忘记",
    .example = "Ich habe meinen Schlüssel vergessen.", .example_cn = "我忘带钥匙了。",},
    {.german = "erlauben", .phonetic = "ɛɐ̯ˈlaʊbn̩",
    .chinese = "允许",
    .example = "Darf ich hier parken? Erlaubt!", .example_cn = "我能在这里停车吗？",},
    {.german = "wichtig", .phonetic = "ˈvɪçtɪç",
    .chinese = "重要的",
    .example = "Termin ist sehr wichtig.", .example_cn = "这个预约很重要。",},
    {.german = "teuer", .phonetic = "ˈtɔʏɐɐ",
    .chinese = "昂贵的",
    .example = "Das Handy ist zu teuer.", .example_cn = "这手机太贵了。",},
    {.german = "billig", .phonetic = "ˈbɪlɪç",
    .chinese = "便宜的",
    .example = "Die Jacke war billig.", .example_cn = "这件夹克很便宜。",},
    {.german = "einfach", .phonetic = "ˈaɪnfax",
    .chinese = "简单的；仅仅",
    .example = "Die Übung ist ganz einfach.", .example_cn = "这个练习很简单。",},
    {.german = "schwierig", .phonetic = "ˈʃviːʁɪç",
    .chinese = "困难的",
    .example = "Die Prüfung war schwierig.", .example_cn = "考试很难。",},
    {.german = "pünktlich", .phonetic = "ˈpœŋktlɪç",
    .chinese = "准时的",
    .example = "Er kommt immer pünktlich.", .example_cn = "他总是很准时。",},
    {.german = "vielleicht", .phonetic = "fiˈlaɪçt",
    .chinese = "也许；可能",
    .example = "Vielleicht regnet es später.", .example_cn = "也许待会儿会下雨。",},
};

static const gl_word_t GL_B1[] = {
    {.german = "die Meinung", .phonetic = "diː ˈmaɪnʊŋ",
    .chinese = "观点；意见",
    .example = "Meiner Meinung nach ist der Plan gut.", .example_cn = "在我看来这个计划不错。",},
    {.german = "die Erfahrung", .phonetic = "diː ɛɐ̯ˈfaːʁʊŋ",
    .chinese = "经验",
    .example = "Sie hat viel Erfahrung im Verkauf.", .example_cn = "她有丰富的销售经验。",},
    {.german = "die Möglichkeit", .phonetic = "diː ˈmœglɪçkaɪt",
    .chinese = "可能性",
    .example = "Es gibt viele Möglichkeiten.", .example_cn = "有很多可能性。",},
    {.german = "die Entscheidung", .phonetic = "diː ɛntˈʃaɪdʊŋ",
    .chinese = "决定",
    .example = "Das war eine schwierige Entscheidung.", .example_cn = "这是一个艰难的决定。",},
    {.german = "die Entwicklung", .phonetic = "diː ɛntˈvɪklʊŋ",
    .chinese = "发展",
    .example = "Die Entwicklung der Technik geht schnell.", .example_cn = "技术发展很快。",},
    {.german = "die Gesellschaft", .phonetic = "diː gəˈzɛlʃaft",
    .chinese = "社会",
    .example = "Die Gesellschaft verändert sich.", .example_cn = "社会在变化。",},
    {.german = "die Wirtschaft", .phonetic = "diː ˈvɪʁtʃaft",
    .chinese = "经济",
    .example = "Die Wirtschaft wächst langsam.", .example_cn = "经济缓慢增长。",},
    {.german = "die Verantwortung", .phonetic = "diː fɛɐ̯ˈantvɔʁtʊŋ",
    .chinese = "责任",
    .example = "Er übernimmt die Verantwortung.", .example_cn = "他承担责任。",},
    {.german = "der Erfolg", .phonetic = "deːɐ̯ ɛɐ̯ˈfɔlk",
    .chinese = "成功",
    .example = "Hartes Training führt zum Erfolg.", .example_cn = "刻苦训练带来成功。",},
    {.german = "der Unterschied", .phonetic = "deːɐ̯ ˈʊntɐʃiːt",
    .chinese = "区别；差异",
    .example = "Es gibt einen großen Unterschied.", .example_cn = "有很大的区别。",},
    {.german = "der Vorteil", .phonetic = "deːɐ̯ ˈvɔʁtaɪl",
    .chinese = "优点；好处",
    .example = "Der Vorteil ist die Lage.", .example_cn = "优点是位置好。",},
    {.german = "der Nachteil", .phonetic = "deːɐ̯ ˈnaːxtaɪl",
    .chinese = "缺点",
    .example = "Der Nachteil ist der Preis.", .example_cn = "缺点是价格。",},
    {.german = "der Grund", .phonetic = "deːɐ̯ ɡʁʊnt",
    .chinese = "原因；理由",
    .example = "Aus welchem Grund kommst du später?", .example_cn = "你为什么晚点来？",},
    {.german = "die Folge", .phonetic = "diː ˈfɔlɡə",
    .chinese = "后果；结果",
    .example = "Die Folge war ein Streit.", .example_cn = "结果是一场争吵。",},
    {.german = "die Beziehung", .phonetic = "diː bəˈtsiːʊŋ",
    .chinese = "关系",
    .example = "Die beiden haben eine gute Beziehung.", .example_cn = "两人关系很好。",},
    {.german = "der Vertrag", .phonetic = "deːɐ̯ fɛɐ̯ˈtʁaːk",
    .chinese = "合同",
    .example = "Ich habe den Vertrag unterschrieben.", .example_cn = "我签了合同。",},
    {.german = "die Bewerbung", .phonetic = "diː bəˈvɛʁbʊŋ",
    .chinese = "求职申请",
    .example = "Sie schreibt eine Bewerbung.", .example_cn = "她在写求职申请。",},
    {.german = "die Ausbildung", .phonetic = "diː ˈaʊsbɪldʊŋ",
    .chinese = "职业培训；教育",
    .example = "Die Ausbildung dauert drei Jahre.", .example_cn = "培训为期三年。",},
    {.german = "die Umfrage", .phonetic = "diː ˈʊmfʁaːɡə",
    .chinese = "问卷调查",
    .example = "Die Umfrage zeigt ein klares Ergebnis.", .example_cn = "调查结果很明确。",},
    {.german = "diskutieren", .phonetic = "dɪsˈkuːtiːʁən",
    .chinese = "讨论",
    .example = "Wir diskutieren über das Projekt.", .example_cn = "我们讨论这个项目。",},
    {.german = "empfehlen", .phonetic = "ɛmˈpfeːlən",
    .chinese = "推荐",
    .example = "Ich kann dieses Restaurant empfehlen.", .example_cn = "我推荐这家餐厅。",},
    {.german = "entscheiden", .phonetic = "ɛntˈʃaɪdən",
    .chinese = "决定",
    .example = "Sie entscheidet sich für den Job.", .example_cn = "她决定做这份工作。",},
    {.german = "unternehmen", .phonetic = "ˌʊntɐˈneːmən",
    .chinese = "从事；采取",
    .example = "Wir müssen etwas unternehmen.", .example_cn = "我们必须采取行动。",},
    {.german = "übernehmen", .phonetic = "yːbɐˈneːmən",
    .chinese = "接管；承担",
    .example = "Er übernimmt eine neue Aufgabe.", .example_cn = "他承担一项新任务。",},
    {.german = "verbessern", .phonetic = "fɛɐ̯ˈbɛsɐn",
    .chinese = "改善；改错",
    .example = "Ich möchte mein Deutsch verbessern.", .example_cn = "我想提高我的德语。",},
    {.german = "erreichen", .phonetic = "ɛɐ̯ˈaɪçən",
    .chinese = "达到；联系上",
    .example = "Wir erreichen das Ziel bald.", .example_cn = "我们很快达到目标。",},
};

const gl_word_t *const GL_LEVEL_TABLE[] = {
    GL_A1, GL_A2, GL_B1,
};

const uint16_t GL_LEVEL_COUNTS[] = {
    50, 36, 26,
};

const uint16_t GL_WORD_TOTAL = 112;
